version: '3'
services:
      grafana:
          image: grafana/grafana:latest
          container_name: grafana
          environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource,vonage-status-panel
            - TZ=America/Sao_Paulo
          volumes:
            - ./config/grafana/var/lib/grafana:/var/lib/grafana
            - ./config/grafana/var/log/grafana:/var/log/grafana
          restart: always
          ports:
            - "3000:3000"
          network_mode: host
      prometheus:
          image: prom/prometheus:latest
          container_name: prometheus
          user: "0"
          ports:
            - "9090:9090"
          volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          restart: always
          network_mode: host
